language: python

matrix:
    include:
        - os: linux
          python: 2.7
          sudo: required
          dist: trusty
          env:
              - PY=2.7

        - os: linux
          python: 3.6
          sudo: required
          dist: trusty
          env:
              - PY=3.6

        - os: osx
          language: generic
          env:
              - PY_VERSION=2.7

        - os: osx
          language: generic
          env:
              - PY_VERSION=3.6

before_install:
    - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo apt-get -qq update;
          sudo apt-get install -y \
            libportmidi-dev \
            libsdl-image1.2-dev \
            libsdl-mixer1.2-dev \
            libsdl-ttf2.0-dev \
            libsdl1.2-dev \
            libsoundtouch-dev \
            libvorbis-dev
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update;
          brew install \
            glib \
            libvorbis \
            portmidi \
            sdl \
            sdl_image \
            sdl_mixer \
            sdl_ttf;
          # soundtouch
          wget https://www.surina.net/soundtouch/soundtouch-2.0.0.zip;
          unzip soundtouch-2.0.0.zip;
          cd soundtouch;
          ./bootstrap;
          ./configure;
          make;
          make install;
          cd ..;
      fi

install:
    - |
      if [[ "$PY_VERSION" == "3.6" ]]; then
        brew install python3;
        pip3 install virtualenv;
        python3 -m virtualenv venv;
        source venv/bin/activate;
      elif [[ "$PY_VERSION" == "2.7" ]]; then
        python2 -m virtualenv venv;
        source venv/bin/activate;
      fi
    - python --version
    - pip --version
    - pip install --upgrade pip wheel
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install -U py; fi  # for pytest
    - pip install cython

before_script:
    - (cd fretwork && python setup.py sdist bdist_wheel)
    - (cd fretwork && pip wheel -w wheelhouse --no-deps .)
    - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        # auditwheel
        if [[ "$PY" == "2.7" ]]; then
            ## python3 virtualenv
            virtualenv -p python3 venv
            source venv/bin/activate
            python --version
        fi
        ## install patchelf
        PATCHELF_VERSION=6bfcafbba8d89e44f9ac9582493b4f27d9d8c369
        curl -sL -o patchelf.tar.gz https://github.com/NixOS/patchelf/archive/$PATCHELF_VERSION.tar.gz
        tar -xzf patchelf.tar.gz
        (cd patchelf-$PATCHELF_VERSION && ./bootstrap.sh && ./configure && make && sudo make install)
        rm -rf patchelf.tar.gz patchelf-$PATCHELF_VERSION
        ## install
        pip install auditwheel
        ## repair
        for whl in fretwork/dist/*.whl; do
            echo $whl
            auditwheel repair $whl -w out/
        done
        chmod -R a+rwX out
        if [[ "$PY" == "2.7" ]]; then
            deactivate
            source ~/virtualenv/python2.7/bin/activate
        fi

      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        # delocate
        ## install
        pip install delocate
        ## list lib dependencies
        delocate-listdeps fretwork/dist/*.whl
        echo in repair_wheelhouse, executing delocate-wheel
        ## copies lib dependencies into wheel
        delocate-wheel fretwork/dist/*.whl
        ## add platform tags
        delocate-addplat --rm-orig -x 10_9 -x 10_10 fretwork/dist/*.whl
        mv fretwork/dist out
      fi
    - echo `ls -l out`

script:
    - pip install out/*.whl
    - pip install pytest
    - pytest fretwork/tests
    - python -c "from fretwork import mixstream"
